const CACHE_NAME = 'english-journey-shell-v1.2.0';
const CORE = ['./','./index.html','./manifest.webmanifest','./icons/icon.svg'];
const SUPABASE_CDN = 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/dist/umd/supabase.min.js';
self.addEventListener('install', event => { event.waitUntil((async () => { const cache=await caches.open(CACHE_NAME); await cache.addAll(CORE); try { const response=await fetch(SUPABASE_CDN,{mode:'cors'}); if(response.ok) await cache.put(SUPABASE_CDN,response.clone()); } catch {} await self.skipWaiting(); })()); });
self.addEventListener('activate', event => { event.waitUntil((async () => { const names=await caches.keys(); await Promise.all(names.filter(name=>name.startsWith('english-journey-')&&name!==CACHE_NAME).map(name=>caches.delete(name))); await self.clients.claim(); })()); });
self.addEventListener('fetch', event => { const request=event.request; if(request.method!=='GET') return; const url=new URL(request.url); if(url.hostname.endsWith('.supabase.co')) return; if(request.mode==='navigate'){ event.respondWith((async()=>{ try { const response=await fetch(request); if(response.ok){const cache=await caches.open(CACHE_NAME); await cache.put('./index.html',response.clone());} return response; } catch { return (await caches.match('./index.html')) || (await caches.match('./')) || Response.error(); } })()); return; } if(request.url===SUPABASE_CDN){ event.respondWith((async()=>{ const cached=await caches.match(request); const network=fetch(request).then(async response=>{ if(response.ok){const cache=await caches.open(CACHE_NAME); await cache.put(request,response.clone());} return response; }).catch(()=>null); return cached || (await network) || Response.error(); })()); return; } if(url.origin===self.location.origin){ event.respondWith((async()=>{ const cached=await caches.match(request); if(cached) return cached; try { const response=await fetch(request); if(response.ok){const cache=await caches.open(CACHE_NAME); await cache.put(request,response.clone());} return response; } catch { return Response.error(); } })()); } });
self.addEventListener('message', event => {
  if (event.data?.type === 'SKIP_WAITING') self.skipWaiting();
});
